apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    metadata:
      labels:
        job: pythonjob
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pythonmain
          image: chaseleasy/pymain:job
   
