apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels: 
    env: prod
    creation_method: manual
spec:
  nodeSelector:
    redis: "true"
  containers:
  - image: chaseleasy/nginx-php:1.1
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP 
