apiVersion: v1
kind: Pod
metadata:
  name: pymain-volume
  labels:
    app: nginx
spec:
  containers:
    - image: chaseleasy/pymain:volumev4
      name: pymain-gen
      volumeMounts:
        - name: html
          mountPath: /data/wwwroot
    
    - image: nginx:1.14-alpine
      name: pymain-get
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true 
      ports:
        - containerPort: 80
   
  volumes:
    - name: html
      emptyDir: {}
     
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
    app: nginx-service
spec:
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30061
  selector:
     app: nginx
  
   
 
  #
