apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
    - image: mongo
      name: mongodb 
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      ports:
        - containerPort: 27017
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:
         claimName: mongodb-pvc

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - image: mysql:5.7
      name: mysql
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456.."
  volumes:
    - name: mysql-data
      persistentVolumeClaim:
         claimName: mysql-pvc
