apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd
spec: 
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      nodeSelector:
        ssd: "true"
      containers:
        - name: main
          image: chaseleasy/pymain:v1
