apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
  labels:
    name: pod-with-configmap
spec:
  containers:
    - image: chaseleasy/pymain:configv2
      name: pod-with-configmap
      env:
       - name: tutu
         valueFrom:
           configMapKeyRef:
              name: pymain-config
              key: tutu
       - name: lanlingwang
         valueFrom:
           configMapKeyRef:
             name: pymain-config
             key: lanlingwang
       - name: anqila
         valueFrom:
           configMapKeyRef:
             name: pymain-config
             key: anqila

---
apiVersion: v1
kind: Service
metadata:
  name: pod-with-configmap-service
spec:
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
  selector:
    name: pod-with-configmap
