apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap-v2
  labels:
    name: pod-with-configmap-v2
spec:
  containers:
    - image: chaseleasy/pymain:configv2
      name: pod-with-configmap-v2
      envFrom:
        - configMapRef:
            name: pymain-config

---
apiVersion: v1
kind: Service
metadata:
  name: pod-with-configmap-v2-service
spec:
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
  selector:
    name: pod-with-configmap-v2
